# Generated by Django 4.2.2 on 2023-06-15 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='color',
            field=models.CharField(default=1, max_length=10, verbose_name='Color'),
            preserve_default=False,
        ),
    ]
